{"name": "test_div[get_datas_div1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 2\n  +None\n  -2", "trace": "self = <pytest_combat.testcases.test_calcu_new.TestCalc object at 0x000001E3CCDE0AC0>, get_calc = <pytest_combat.api.calculator.Calculator object at 0x000001E3CCD76040>\nget_datas_div = [2, 0, 2]\n\n    @pytest.mark.fourth\n    def test_div(self,get_calc,get_datas_div):\n        result = None\n        try:\n            result = get_calc.div(get_datas_div[0], get_datas_div[1])\n        except Exception as e_div:\n            print(\"division by zero\")\n    \n>       assert result == get_datas_div[2]\nE       assert None == 2\nE         +None\nE         -2\n\ntest_calcu_new.py:28: AssertionError"}, "parameters": [{"name": "get_datas_div", "value": "[2, 0, 2]"}], "start": 1622384497774, "stop": 1622384497775, "uuid": "89809225-5c01-4d91-a65d-feb75affb469", "historyId": "21ef385d47b9a08aa3e02ad7059778ec", "testCaseId": "75a83c0ea9b614edd11501ec0514139c", "fullName": "pytest_combat.testcases.test_calcu_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "fourth"}, {"name": "parentSuite", "value": "pytest_combat.testcases"}, {"name": "suite", "value": "test_calcu_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-EP4FUOH"}, {"name": "thread", "value": "11752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_combat.testcases.test_calcu_new"}]}