{"name": "test_add[exception]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'a'\n  +None\n  -'a'", "trace": "self = <pytest_combat.testcases.test_calcu_new.TestCalc object at 0x0000019E232587C0>, get_calc = <pytest_combat.api.calculator.Calculator object at 0x0000019E231EFD30>\nget_datas = ['', 5, 'a']\n\n    def test_add(self,get_calc,get_datas):\n        result = None\n        try:\n            #用fixture方法名返回计算器实例并调用计算器中的方法add\n            result = get_calc.add(get_datas[0], get_datas[1])\n            if isinstance(result,float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n    \n    \n>       assert result == get_datas[2]\nE       AssertionError: assert None == 'a'\nE         +None\nE         -'a'\n\ntest_calcu_new.py:19: AssertionError"}, "parameters": [{"name": "get_datas", "value": "['', 5, 'a']"}], "start": 1622350694475, "stop": 1622350694477, "uuid": "76af3212-7889-42b1-833c-bd866976a134", "historyId": "612c39b3f7e190fa2fa36d5e29d80b58", "testCaseId": "9117aa56cd4623e5c949e74de2331c8a", "fullName": "pytest_combat.testcases.test_calcu_new.TestCalc#test_add", "labels": [{"name": "parentSuite", "value": "pytest_combat.testcases"}, {"name": "suite", "value": "test_calcu_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-EP4FUOH"}, {"name": "thread", "value": "2032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_combat.testcases.test_calcu_new"}]}